In [75]:
#importing necesarry library
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt



In [76]:
#loading dataframe
cd=pd.read_csv("CAR DETAILS FROM CAR DEKHO.csv")

In [77]:
#top 5 rws
cd.head(12)

name  year  selling_price  km_driven    fuel  \
0               Maruti 800 AC  2007          60000      70000  Petrol   
1    Maruti Wagon R LXI Minor  2007         135000      50000  Petrol   
2        Hyundai Verna 1.6 SX  2012         600000     100000  Diesel   
3      Datsun RediGO T Option  2017         250000      46000  Petrol   
4       Honda Amaze VX i-DTEC  2014         450000     141000  Diesel   
5        Maruti Alto LX BSIII  2007         140000     125000  Petrol   
6   Hyundai Xcent 1.2 Kappa S  2016         550000      25000  Petrol   
7    Tata Indigo Grand Petrol  2014         240000      60000  Petrol   
8    Hyundai Creta 1.6 VTVT S  2015         850000      25000  Petrol   
9    Maruti Celerio Green VXI  2017         365000      78000     CNG   
10    Chevrolet Sail 1.2 Base  2015         260000      35000  Petrol   
11   Tata Indigo Grand Petrol  2014         250000     100000  Petrol   

   seller_type transmission         owner  
0   Individual       Manual   First Owner  
1   Individual       Manual   First Owner  
2   Individual       Manual   First Owner  
3   Individual       Manual   First Owner  
4   Individual       Manual  Second Owner  
5   Individual       Manual   First Owner  
6   Individual       Manual   First Owner  
7   Individual       Manual  Second Owner  
8   Individual       Manual   First Owner  
9   Individual       Manual   First Owner  
10  Individual       Manual   First Owner  
11  Individual       Manual   First Owner

In [4]:
#counting different car present in dataset
cd.name.value_counts()

Maruti Swift Dzire VDI                  69
Maruti Alto 800 LXI                     59
Maruti Alto LXi                         47
Hyundai EON Era Plus                    35
Maruti Alto LX                          35
                                        ..
Ford Classic 1.6 Duratec LXI             1
Ford Fiesta 1.4 SXi TDCi                 1
Hyundai Santa Fe 4WD AT                  1
Ford Endeavour 4x2 XLT                   1
Tata Manza Club Class Quadrajet90 EX     1
Name: name, Length: 1491, dtype: int64

In [5]:
#knowing how many year old car is before selling it
cd['yr_old']=2020-cd.year

In [6]:
#top 5 rows after ading one extra column and adding more column in a dataset is called as feature engineering
cd.head()

name  year  selling_price  km_driven    fuel  \
0             Maruti 800 AC  2007          60000      70000  Petrol   
1  Maruti Wagon R LXI Minor  2007         135000      50000  Petrol   
2      Hyundai Verna 1.6 SX  2012         600000     100000  Diesel   
3    Datsun RediGO T Option  2017         250000      46000  Petrol   
4     Honda Amaze VX i-DTEC  2014         450000     141000  Diesel   

  seller_type transmission         owner  yr_old  
0  Individual       Manual   First Owner      13  
1  Individual       Manual   First Owner      13  
2  Individual       Manual   First Owner       8  
3  Individual       Manual   First Owner       3  
4  Individual       Manual  Second Owner       6

In [7]:
#information about datafield
cd.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4340 entries, 0 to 4339
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   name           4340 non-null   object
 1   year           4340 non-null   int64 
 2   selling_price  4340 non-null   int64 
 3   km_driven      4340 non-null   int64 
 4   fuel           4340 non-null   object
 5   seller_type    4340 non-null   object
 6   transmission   4340 non-null   object
 7   owner          4340 non-null   object
 8   yr_old         4340 non-null   int64 
dtypes: int64(4), object(5)
memory usage: 305.3+ KB


In [8]:
#checking if there is any null value
cd.isna().sum()

name             0
year             0
selling_price    0
km_driven        0
fuel             0
seller_type      0
transmission     0
owner            0
yr_old           0
dtype: int64

In [9]:
#summarizing the dataset..
cd.describe()

year  selling_price      km_driven       yr_old
count  4340.000000   4.340000e+03    4340.000000  4340.000000
mean   2013.090783   5.041273e+05   66215.777419     6.909217
std       4.215344   5.785487e+05   46644.102194     4.215344
min    1992.000000   2.000000e+04       1.000000     0.000000
25%    2011.000000   2.087498e+05   35000.000000     4.000000
50%    2014.000000   3.500000e+05   60000.000000     6.000000
75%    2016.000000   6.000000e+05   90000.000000     9.000000
max    2020.000000   8.900000e+06  806599.000000    28.000000

In [10]:
#dropping unnecessary column
cd=cd.drop(['name','year'],axis=1)

In [11]:
cd

selling_price  km_driven    fuel seller_type transmission         owner  \
0             60000      70000  Petrol  Individual       Manual   First Owner   
1            135000      50000  Petrol  Individual       Manual   First Owner   
2            600000     100000  Diesel  Individual       Manual   First Owner   
3            250000      46000  Petrol  Individual       Manual   First Owner   
4            450000     141000  Diesel  Individual       Manual  Second Owner   
...             ...        ...     ...         ...          ...           ...   
4335         409999      80000  Diesel  Individual       Manual  Second Owner   
4336         409999      80000  Diesel  Individual       Manual  Second Owner   
4337         110000      83000  Petrol  Individual       Manual  Second Owner   
4338         865000      90000  Diesel  Individual       Manual   First Owner   
4339         225000      40000  Petrol  Individual       Manual   First Owner   

      yr_old  
0         13  
1         13  
2          8  
3          3  
4          6  
...      ...  
4335       6  
4336       6  
4337      11  
4338       4  
4339       4  

[4340 rows x 7 columns]

In [12]:
cd=cd[cd.fuel!="Electric"]

In [13]:
cd.fuel.value_counts()

Diesel    2153
Petrol    2123
CNG         40
LPG         23
Name: fuel, dtype: int64

In [14]:
#since we should always have continous or descrete value to feed into ML model so we are converting string value to descrete value
dict1={"Petrol":0,"Diesel":1,"CNG":2,"LPG":3}
cd.fuel=cd.fuel.map(dict1)

c:\users\asus\anaconda32\lib\site-packages\pandas\core\generic.py:5168: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[name] = value


In [15]:
cd.fuel.value_counts()

1    2153
0    2123
2      40
3      23
Name: fuel, dtype: int64

In [16]:
cd.head()

selling_price  km_driven  fuel seller_type transmission         owner  \
0          60000      70000     0  Individual       Manual   First Owner   
1         135000      50000     0  Individual       Manual   First Owner   
2         600000     100000     1  Individual       Manual   First Owner   
3         250000      46000     0  Individual       Manual   First Owner   
4         450000     141000     1  Individual       Manual  Second Owner   

   yr_old  
0      13  
1      13  
2       8  
3       3  
4       6

In [17]:
cd.seller_type.value_counts()

Individual          3244
Dealer               993
Trustmark Dealer     102
Name: seller_type, dtype: int64

In [18]:
dict1={"Individual":0,"Dealer":1,"Trustmark Dealer":2}
cd.seller_type=cd.seller_type.map(dict1)

c:\users\asus\anaconda32\lib\site-packages\pandas\core\generic.py:5168: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[name] = value


In [19]:
cd.head()

selling_price  km_driven  fuel  seller_type transmission         owner  \
0          60000      70000     0            0       Manual   First Owner   
1         135000      50000     0            0       Manual   First Owner   
2         600000     100000     1            0       Manual   First Owner   
3         250000      46000     0            0       Manual   First Owner   
4         450000     141000     1            0       Manual  Second Owner   

   yr_old  
0      13  
1      13  
2       8  
3       3  
4       6

In [20]:
cd.transmission.value_counts()

Manual       3892
Automatic     447
Name: transmission, dtype: int64

In [21]:
dict1={"Manual":0,"Automatic":1}
cd.transmission=cd.transmission.map(dict1)

c:\users\asus\anaconda32\lib\site-packages\pandas\core\generic.py:5168: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[name] = value


In [22]:
cd.head()

selling_price  km_driven  fuel  seller_type  transmission         owner  \
0          60000      70000     0            0             0   First Owner   
1         135000      50000     0            0             0   First Owner   
2         600000     100000     1            0             0   First Owner   
3         250000      46000     0            0             0   First Owner   
4         450000     141000     1            0             0  Second Owner   

   yr_old  
0      13  
1      13  
2       8  
3       3  
4       6

In [23]:
cd.owner.value_counts()

First Owner             2832
Second Owner            1105
Third Owner              304
Fourth & Above Owner      81
Test Drive Car            17
Name: owner, dtype: int64

In [24]:
dict1={"First Owner":1,"Second Owner":2,"Third Owner":3,"Fourth & Above Owner":4,"Test Drive Car":0}
cd.owner=cd.owner.map(dict1)

c:\users\asus\anaconda32\lib\site-packages\pandas\core\generic.py:5168: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[name] = value


In [25]:
cd.owner.value_counts()

1    2832
2    1105
3     304
4      81
0      17
Name: owner, dtype: int64

In [26]:
#Now there is no string value and our dataset is ready to feed into model...
cd.head()

selling_price  km_driven  fuel  seller_type  transmission  owner  yr_old
0          60000      70000     0            0             0      1      13
1         135000      50000     0            0             0      1      13
2         600000     100000     1            0             0      1       8
3         250000      46000     0            0             0      1       3
4         450000     141000     1            0             0      2       6

In [60]:
#independent variable
x=cd.drop(['selling_price'],axis=1
         )
x

km_driven  fuel  seller_type  transmission  owner  yr_old
0         70000     0            0             0      1      13
1         50000     0            0             0      1      13
2        100000     1            0             0      1       8
3         46000     0            0             0      1       3
4        141000     1            0             0      2       6
...         ...   ...          ...           ...    ...     ...
4335      80000     1            0             0      2       6
4336      80000     1            0             0      2       6
4337      83000     0            0             0      2      11
4338      90000     1            0             0      1       4
4339      40000     0            0             0      1       4

[4339 rows x 6 columns]

In [61]:
#dependent variable
y=cd[['selling_price']]
y

selling_price
0             60000
1            135000
2            600000
3            250000
4            450000
...             ...
4335         409999
4336         409999
4337         110000
4338         865000
4339         225000

[4339 rows x 1 columns]

In [62]:
#for splitting the dataset into training and testset
from sklearn.model_selection import train_test_split

In [31]:
#split the data into train and test set
train_x,test_x,train_y,test_y=train_test_split(x,y,test_size=0.3)

In [63]:
#importing linear regression
from sklearn.linear_model import LinearRegression

In [64]:
#making object of the model
lr=LinearRegression()

In [65]:
#fitting training data into our model
lr.fit(train_x,train_y)

LinearRegression()

In [66]:
#predicting output
pred=lr.predict(test_x)
pred

array([[ 337076.78289661],
       [  71074.80878896],
       [1376835.06618432],
       ...,
       [ 448383.86950675],
       [ 395861.62274945],
       [ 667016.47350889]])

In [67]:
#accuracy score 
pr=lr.score(train_x,train_y)
pr*100

44.77274429976009

In [68]:
lr.predict([[20,0,0,0,1,3]])

array([[481887.34770208]])

In [69]:
#since accuracy was not good so we will use decision tree
from sklearn.tree import DecisionTreeRegressor

In [70]:
dtr=DecisionTreeRegressor()

In [71]:
dtr.fit(train_x,train_y)

DecisionTreeRegressor()

In [72]:
dtr.predict(test_x)

array([169000. ,  85000. , 462500. , ..., 362500. , 325000. , 774499.9])

In [73]:
dtr.score(train_x,train_y)

0.962938730014518

In [45]:
dtr.predict([[20,0,0,0,1,3]])

array([688000.])

In [46]:
from sklearn.ensemble import RandomForestRegressor

In [47]:
rfr=RandomForestRegressor()

In [48]:
rfr.fit(train_x,train_y)

<ipython-input-48-3488a897feb3>:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rfr.fit(train_x,train_y)


RandomForestRegressor()

In [49]:
rfr.predict(test_x)

array([168115.88888889, 179308.29333333, 668847.61904762, ...,
       546837.25      , 318623.33333333, 774566.09431011])

In [50]:
rfr.score(train_x,train_y)

0.9233663302708203

In [74]:
#used to store/save the model so that it can be used in future
import pickle
with open("model.pkl","wb") as f:
    pickle.dump(dtr,f)